---

swap_file_enabled: yes
swap_file_path: /swap
swap_file_size_mb: 2048

permit_root_login: true

users:
  - name: "pavelkim"
    shell: "/bin/bash"
    groups: "wheel"
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/IsmDgWqNct6LCv3oj3G7dewoUzPcVzeastNLfl++qc24ABV2CHJpWDuDkcgq7ASC4jJKiETXSRsA48gFYaj0cIUrIiMxW+m5G0qvKsG/w9LQ8LXJXzSkVvgYRHF/HZWiUuq1j3JEtX4KlpOda8eDMdeRcNuxFGywsuQefLeCwfcGxKA6tfOwYn9GEASjPQyOXNfEDoheB0QcvmaQPeGX8kD6K+Ndqe7E/OKcYSFjUfysrPkk0EE4BaYVLN1fvGIPcaIcJzT7jc37YTVx9h/vkDIANErVpap+mHz2Ec079HgcMrRk3qjGrdTAv2qN1gC2G/dIe0anXjNWMjKq04Sj pavelkim@laptop"
    extra_ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKC6ix0HWXd3yH+Y9ZFK2wcSO7jz6SUykKLSJww7Zt/dUtWvScpLyj0gRoiVOeXebVwP/PKtIuR55STYKvvTjtq18VsjxQz0pQHPwgXArEBK7yjOfUkxKE0nZrfkO6PLcbnlU9m+XvcN9aOM4GMX/+GiSXSFO+o1cUYpz6nY51TFfMopuBqWAk+VdE67azMsk9o60xbvEhI2C0m41myaEbH0v5iNN2jZocNNTmtI0plVcWTGi4mNKoE/Z0lFm87WBP/pgkuK5Vls2Oy93IDuLxqzbd773jxwRGA3i9plcBTa22SERpSdwzu4nC1FB+YfbEkhDOGdIcPKIxWvwnqNNzT2TVXuAA3F0LWJVZrLyesvm5AtdYmXRwoj5Ty5PKwZH1NdzfcX+oOj6mBWtwt3poBkWMfzIegTHCIALxClxy7fr1EkxRCh3TIRXkGfilssViEW4vyan34/O88DkO0epGHQqU/dApVNbKc6X47b2jRkHe5UYRuRcT/fuH4Vyk0Ac= pavelkim@marge"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWiL0/2nSsj1huD4LwDZMXRjg8iIiqd0N68gKwlEmJSE4CVS//eyNtxwj8siMJDEXdVWBMsf8MS27sUYG/S7ibk/PkIUIuoL95lIujBQ/TEdcdYzfFWXcXhVaxY9WcQvSH7l1j4W91jpf45qrvPNyUPPjXAIjd/U8WNMY3xFo14is/qzP9ly+Tk9RrjeZxxhgDP4wM65wbfE/xNamda/eB+ZIPq3t7WLY7Pw/yVdpTFwMLD16qMol1gpRdR1wlYJ84RWCW7vs67OsHHpqqFCNi6A8CYIkapNAl7LY3dpAriM+rwoCAsJQp0/A8qEsvaDnydI1Yz2UOaC23fB8V4JX5 pavelkim@v2"

  - name: "ghr"
    shell: "/bin/bash"
    groups: "wheel"
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILKF94wuU4G+Lr2qZyawGGsFp45Oo0k/EQL6HhtNyFiM"
    extra_ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/IsmDgWqNct6LCv3oj3G7dewoUzPcVzeastNLfl++qc24ABV2CHJpWDuDkcgq7ASC4jJKiETXSRsA48gFYaj0cIUrIiMxW+m5G0qvKsG/w9LQ8LXJXzSkVvgYRHF/HZWiUuq1j3JEtX4KlpOda8eDMdeRcNuxFGywsuQefLeCwfcGxKA6tfOwYn9GEASjPQyOXNfEDoheB0QcvmaQPeGX8kD6K+Ndqe7E/OKcYSFjUfysrPkk0EE4BaYVLN1fvGIPcaIcJzT7jc37YTVx9h/vkDIANErVpap+mHz2Ec079HgcMrRk3qjGrdTAv2qN1gC2G/dIe0anXjNWMjKq04Sj pavelkim@laptop"

...
