---

macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

prepare_and_build_task:
  name: Prepare environment and build
  only_if: $CIRRUS_BRANCH =~ 'build_.*'
  environment:
    ARTIFACTORY_RW_TOKEN: ENCRYPTED[!0b4f793daee14bc59cc8d5e42e8fbd0cae5b7c2e94e5ace6fec815999058cc2d14804ec0b0eedd8b402c182c7b7acd88!]
    ARTIFACTORY_REPO_URL: ENCRYPTED[!2570f878f406c2bf1264238eeda0507248b1ec7a29f9a950ce5c0dd56fd7f57e4e05c78360bdfca334cc0026ac7c805b!]
    ARTIFACT_TARGZ_NAME: ""
    APP_NAME: tdlib
    ARCH: arm64
    OS: macos13

  fetch_version_script:
    - export PLANNED_VERSION=$( cat .version )
    - export ARTIFACT_TARGZ_NAME="${APP_NAME}-${PLANNED_VERSION}-${OS}-${ARCH}.tar.gz"
    - echo "export PLANNED_VERSION='${PLANNED_VERSION}'" >> ~/.zshrc
    - echo "export ARTIFACT_TARGZ_NAME='${ARTIFACT_TARGZ_NAME}'" >> ~/.zshrc

  install_dependencies_script:
    - source ~/.zshrc
    - bash sbin/macos-13/install-dependencies.sh

  checkout_td_script: 
    - source ~/.zshrc
    - mkdir -pv td
    - git clone https://github.com/tdlib/td.git td
    - ls -lAth .

  build_td_script:
    - source ~/.zshrc
    - bash "sbin/macos-13/build.sh"

  prepare_artifacts_script:
    - source ~/.zshrc
    - mkdir -v "dist"
    - mv -v td/tdlib "dist/"
    - tar -zvcf "${ARTIFACT_TARGZ_NAME}" "dist"

  upload_artifacts_script:
    - source ~/.zshrc
    - >-
      curl
      -o upload_to_artifactory_result.json
      -X PUT
      -H "Authorization: Bearer ${ARTIFACTORY_RW_TOKEN}"
      -T "${ARTIFACT_TARGZ_NAME}"
      "${ARTIFACTORY_REPO_URL}/${APP_NAME}/${ARTIFACT_TARGZ_NAME}"


  list_artifacts_script:
    - source ~/.zshrc
    - >-
      curl
      -o list_artifacts_result.json
      -X GET
      -H "Authorization: Bearer ${ARTIFACTORY_RW_TOKEN}"
      -H "Content-Type: text/plain"
      "${ARTIFACTORY_REPO_URL}/api/search/artifact?repos=${APP_NAME}&name=${PLANNED_VERSION}"


  results_printout_script:
    - jq < upload_to_artifactory_result.json
    - jq < list_artifacts_result.json
    - jq -r '.results[].uri' < list_artifacts_result.json

prepare_and_build_docker_task:
  name: Prepare environment and build Docker image
  only_if: $CIRRUS_BRANCH =~ 'build_arm64_.*'
  environment:
    APP_NAME: tdlib
    ARCH: arm64
    OS: macos13
    DOCKER_OS: alpine-3.18
    DOCKER_PASSWORD: ENCRYPTED[!50d4dbf82dca3a7fead72baadcd3bd2e2e1f9d5448d3bf4e8d6ce2769d412550fa03457a77784a282e3d2b70fd36f5b6!]
    DOCKER_USERNAME: ENCRYPTED[!25aff238fdea08accc0f3d8444ac675374a157781f6d75c4d47ce1966f00d48901a2b22141964345dc07800383b470e2!]

  fetch_version_script:
    - export PLANNED_VERSION=$( cat .version )
    - echo "export PLANNED_VERSION='${PLANNED_VERSION}'" >> ~/.zshrc

  install_dependencies_script:
    - source ~/.zshrc
    - bash sbin/macos-13/install-dependencies-docker.sh

  build_docker_image_script:
    - source ~/.zshrc
    - cd "docker/${DOCKER_OS}"

    - >
      echo "${DOCKER_PASSWORD}" |
      docker login "docker.io"
      -u "${DOCKER_USERNAME}"
      --password-stdin

    - >
      docker build
      --tag "docker.io/reinvented_stuff/tdlib:${PLANNED_VERSION}-${DOCKER_OS}"
      --build-arg BUILD_VERSION="${PLANNED_VERSION}-${DOCKER_OS}"
      --file Dockerfile
      .
    - docker push docker.io/reinvented_stuff/tdlib

...
