---

macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

prepare_and_build_task:
  name: Prepare environment and build
  environment:
    ARTIFACTORY_RW_TOKEN: ENCRYPTED[!7191c70520f2a8e33bf3ce9e0a304da32faf18436e060264c992f769ca6cac6d68b0c2f4bc435d5eb25a2bde5391f08d!]
    ARTIFACTORY_REPO_URL: https://pavelkim.jfrog.io/artifactory
    ARTIFACT_TARGZ_NAME: ""
    APP_NAME: tdlib
    ARCH: arm64
    OS: macos13

  fetch_version_script:
    - export PLANNED_VERSION=$( cat .version )
    - export ARTIFACT_TARGZ_NAME="${APP_NAME}-${PLANNED_VERSION}-${OS}-${ARCH}.tar.gz"

  install_dependencies_script: bash sbin/macos-13/install-dependencies.sh

  checkout_td_script: 
    - mkdir -pv td
    - git clone https://github.com/tdlib/td.git td
    - ls -lAth .

  build_td_script:
    - bash "sbin/macos-13/build.sh"

  prepare_artifacts_script:
    - mkdir -v "dist"
    - mv -v td/tdlib "dist/"
    - tar -zvcf tdlib_macos-13.tar.gz "dist"

  upload_artifacts_script: >-
    curl
    -o upload_to_artifactory_result.json
    -X PUT
    -H "Authorization: Bearer ${ARTIFACTORY_RW_TOKEN}"
    -T "${ARTIFACT_TARGZ_NAME}"
    "${ARTIFACTORY_REPO_URL}/${APP_NAME}/${ARTIFACT_TARGZ_NAME}"


  list_artifacts_script: >-
    curl
    -o list_artifacts_result.json
    -X GET
    -H "Authorization: Bearer ${ARTIFACTORY_RW_TOKEN}"
    -H "Content-Type: text/plain"
    "${ARTIFACTORY_REPO_URL}/api/search/artifact?repos=${APP_NAME}&name=${PLANNED_VERSION}"


  results_printout_script:
    - jq < upload_to_artifactory_result.json
    - jq < list_artifacts_result.json
    - jq -r '.results[].uri' < list_artifacts_result.json

...
