- name: Initialise github runner
  hosts: all
  gather_facts: yes
  become: yes
  strategy: free

  tasks:

    - name: Define Linux version variables
      set_fact:
        linux_os_family: "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}"
        linux_os_distribution: "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"

    - name: Prepare directories
      file:
        path: /opt/actions-runner
        state: directory

    - name: Download actions-runner package
      uri:
        url: https://github.com/actions/runner/releases/download/v2.294.0/actions-runner-linux-x64-2.294.0.tar.gz
        dest: /opt/actions-runner/actions-runner-linux-x64-2.294.0.tar.gz
        follow_redirects: yes
        status_code: [200, 304]

    - name: Unpack actions-runner package
      unarchive:
        src: /opt/actions-runner/actions-runner-linux-x64-2.294.0.tar.gz
        dest: /opt/actions-runner
        remote_src: yes
        owner: ghr
        group: wheel

    - name: Configure actions-runner
      become: yes
      become_user: ghr
      shell:
        chdir: /opt/actions-runner
        cmd: >-
          ./config.sh
          --unattended
          --name "{{ ansible_hostname }}"
          --labels "{{ linux_os_family }}"
          --url https://github.com/reinvented-stuff
          --token "{{ ghr_token }}"

    - name: Setup actions-runner service
      become: yes
      shell:
        chdir: /opt/actions-runner
        cmd: >-
          ./svc.sh install ghr

    - name: Start actions-runner service
      become: yes
      shell:
        chdir: /opt/actions-runner
        cmd: >-
          ./svc.sh start

...
