- name: Initialise github runner
  hosts: all
  gather_facts: yes
  become: yes
  strategy: free

  tasks:

    - name: Fetch extended set of facts
      include_role:
        name: roles/role-linux-base
        apply:
          tags:
            - facts

    - name: Prepare directories
      file:
        path: /opt/actions-runner
        state: directory

    - name: Download actions-runner package
      uri:
        url: https://github.com/actions/runner/releases/download/v2.294.0/actions-runner-linux-x64-2.294.0.tar.gz
        dest: /opt/actions-runner/actions-runner-linux-x64-2.294.0.tar.gz
        follow_redirects: yes
        status_code: [200, 304]

    - name: Unpack actions-runner package
      unarchive:
        src: /opt/actions-runner/actions-runner-linux-x64-2.294.0.tar.gz
        dest: /opt/actions-runner
        remote_src: yes

    - name: Configure actions-runner
      shell:
        chdir: /opt/actions-runner
        cmd: >-
          ./config.sh
          --unattended
          --name "{{ ansible_hostname }}"
          --labels "{{ linux_os_family }}"
          --url https://github.com/reinvented-stuff
          --token "{{ ghr_token }}"
