---

- name: Define Linux version variables
  set_fact:
    linux_os_family: "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}"
    linux_os_distribution: "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
  tags:
    - always

- name: Load OS-specific variables
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      - "vars/{{ linux_os_distribution }}.yml"
      - "vars/{{ linux_os_family }}.yml"
      - default.yml

- name: Print out variables
  debug:
    msg:
      - "ansible_distribution: {{ ansible_distribution }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_os_family: {{ ansible_os_family }}"
      - "linux_os_family: {{ linux_os_family }}"
      - "linux_os_distribution: {{ linux_os_distribution }}"
  tags:
    - debug
    - never

...