---

- name: Setup swap file
  block:

    - name: Create a swap file
      command: dd if=/dev/zero of="{{ swap_file_path }}" bs=1024 count="{{ swap_file_size_mb }}k"
      args:
        creates:
          "{{ swap_file_path }}"

    - name: Set swap file permissions
      file: 
        path: "{{ swap_file_path }}"
        owner: root
        group: root
        mode: 0600

    - name: Check swap file type
      command: file "{{ swap_file_path }}"
      register: swapfile

    - name: Make swap file usable as a swap space
      command: mkswap "{{ swap_file_path }}"
      when: swapfile.stdout.find('swap file') == -1

    - name: Create an entry in fstab for swap file
      mount: 
        name: none
        src: "{{ swap_file_path }}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present

    - name: Mount swap file
      command: swapon --all --ifexists --fixpgsz 

  when:
    - swap_file_enabled | bool == True

  tags:
    - swap

...