---

yum_packages_global:
  - curl
  - curl-devel
  - gzip
  - less
  - lsof
  - mc
  - rsync
  - rsyslog
  - tmux
  - tar
  - tcpdump
  - unzip
  - vim
  - wget
  - at
  - s-nail
  - jq
  - python3-pip
  - bind-utils
  - net-tools
  - podman
  - podman-docker

...
